import javax.swing.*;

/*
 * @author Tucker Parker-Warwick
 * CSC 119 Intro to Programming - JAVA
 * 12/13/2020
 */

public class App extends javax.swing.JPanel {

    //string variables to pass to BMI methods
    String weightString;
    String heightString;
    String calcString;
    String rangeString;

    //Display the BMI calculation to the user
    public static void main(String[] args) {

        //create instance of JFrame
        JFrame frame = new JFrame("Body Mass Index (BMI) Calculator");
        //instantiate Swing components
        frame.setContentPane(new App());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        //set the window to center screen instead of top left
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//end Main() method
    
    /**
     * Creates new form App
     */
    public App() {
        //these come from the auto-generated code
        //calls all components from designer as one method
        initComponents();
        //set label text
        //setText here instead of directly on the components
        //better way would be using String variable to not "hard code" names
        labelParam.setText("Enter the parameters, then press OK.");
        labelHeight.setText("height (inches)");
        labelWeight.setText("weight (lbs.)");

        //set text on OK button
        buttonOk.setText("OK");

    }//end App() constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelParam = new javax.swing.JLabel();
        labelHeight = new javax.swing.JLabel();
        textHeight = new javax.swing.JTextField();
        labelWeight = new javax.swing.JLabel();
        textWeight = new javax.swing.JTextField();
        buttonOk = new javax.swing.JButton();
        labelCalc = new javax.swing.JLabel();
        labelRange = new javax.swing.JLabel();

        setName("mainPanel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(550, 200));

        labelParam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelParam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelHeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textHeight.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        labelWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWeight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textWeight.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        buttonOk.setText("OK");
        buttonOk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        labelCalc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCalc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelRange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRange, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelWeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonOk)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelParam, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelWeight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelRange, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("mainPanel");
    }// </editor-fold>//GEN-END:initComponents

    //sets the event listener to the OK button
    //performs method calls for BMI calculation
    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed

        //create new instance of BMI class
        BMICalculator bmi = new BMICalculator();

        //get text from text fields and assign to strings
        weightString = textWeight.getText();
        heightString = textHeight.getText();
        //pass string values into method
        bmi.getWeightAndHeight(weightString, heightString);

        //calculate BMI and display in label
        labelCalc.setText(bmi.calculateBMI(calcString));
        //determine range and display in label
        labelRange.setText(bmi.bmiRange(rangeString));
        
        //reset text entry
        textHeight.setText("");
        textWeight.setText("");
        
    }//GEN-LAST:event_buttonOkActionPerformed
    //end buttonOKActionPerformed() method
    //netbeans will not allow comment on the end of the curly brace

    //these are auto-generated by NetBeans
    //variable names were set in Properties field of Designer
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOk;
    private javax.swing.JLabel labelCalc;
    private javax.swing.JLabel labelHeight;
    private javax.swing.JLabel labelParam;
    private javax.swing.JLabel labelRange;
    private javax.swing.JLabel labelWeight;
    private javax.swing.JTextField textHeight;
    private javax.swing.JTextField textWeight;
    // End of variables declaration//GEN-END:variables

}//end App class
